### Listagem de produtos
GET http://localhost:5076/api/produto/listar

### Cadastro de produtos
POST http://localhost:5076/api/produto/cadastrar

### Buscar produto
GET http://localhost:5076/api/produto/buscar/Celular